SELECT FEFV.USER_EXECUTABLE_NAME,
FEFV.EXECUTABLE_NAME,
FEFV.APPLICATION_NAME,
FEFV.DESCRIPTION,
FEFV.EXECUTION_METHOD_CODE,
FEFV.EXECUTION_FILE_NAME,
FEFV.SUBROUTINE_NAME,
FEFV.EXECUTION_FILE_PATH,
FEFV.APPLICATION_ID,
FEFV.EXECUTABLE_ID,
FEFV.LAST_UPDATE_DATE,
FEFV.LAST_UPDATED_BY,
FEFV.LAST_UPDATE_LOGIN,
FEFV.CREATION_DATE,
FEFV.CREATED_BY,
FEFV.ROW_ID,
FA.APPLICATION_SHORT_NAME,
'Y' EXIST_FLAG                                                    --檢查1.5年內是否有使用
FROM   FND_EXECUTABLES_FORM_V FEFV,
FND_CONCURRENT_PROGRAMS_VL FCPV,
FND_APPLICATION FA
WHERE  1 = 1
AND FEFV.EXECUTABLE_ID > 4
AND FEFV.APPLICATION_ID = FA.APPLICATION_ID
AND FA.APPLICATION_SHORT_NAME = 'FS'
--      AND      FEFV.EXECUTABLE_NAME = 'ERPFS01010'
AND FEFV.EXECUTABLE_ID = FCPV.EXECUTABLE_ID
AND EXISTS
   (   SELECT 1
       FROM   ERP_SYS_PROGRAM_LOG_V
       WHERE  1 = 1
       AND TRUNC( ACTUAL_START_DATE ) >= TRUNC( SYSDATE ) - 547 --365+365/2 = 1.5
       AND STATUS_CODE IN ('C', 'R')
       AND USER_CONCURRENT_PROGRAM_NAME = FCPV.USER_CONCURRENT_PROGRAM_NAME) --檢查1.5年內是否有使用
UNION
SELECT FEFV.USER_EXECUTABLE_NAME,
FEFV.EXECUTABLE_NAME,
FEFV.APPLICATION_NAME,
FEFV.DESCRIPTION,
FEFV.EXECUTION_METHOD_CODE,
FEFV.EXECUTION_FILE_NAME,
FEFV.SUBROUTINE_NAME,
FEFV.EXECUTION_FILE_PATH,
FEFV.APPLICATION_ID,
FEFV.EXECUTABLE_ID,
FEFV.LAST_UPDATE_DATE,
FEFV.LAST_UPDATED_BY,
FEFV.LAST_UPDATE_LOGIN,
FEFV.CREATION_DATE,
FEFV.CREATED_BY,
FEFV.ROW_ID,
FA.APPLICATION_SHORT_NAME,
'N' EXIST_FLAG                                                    --檢查1.5年內是否有使用
FROM   FND_EXECUTABLES_FORM_V FEFV,
FND_CONCURRENT_PROGRAMS_VL FCPV,
FND_APPLICATION FA
WHERE  1 = 1
AND FEFV.EXECUTABLE_ID > 4
AND FEFV.APPLICATION_ID = FA.APPLICATION_ID
AND FA.APPLICATION_SHORT_NAME = 'FS'
--      AND      FEFV.EXECUTABLE_NAME = 'ERPFS01010'
AND FEFV.EXECUTABLE_ID = FCPV.EXECUTABLE_ID
AND NOT EXISTS
   (   SELECT 1
       FROM   ERP_SYS_PROGRAM_LOG_V
       WHERE  1 = 1
       AND TRUNC( ACTUAL_START_DATE ) >= TRUNC( SYSDATE ) - 547 --365+365/2 = 1.5
       AND STATUS_CODE IN ('C', 'R')
       AND USER_CONCURRENT_PROGRAM_NAME = FCPV.USER_CONCURRENT_PROGRAM_NAME) --檢查1.5年內是否有使用