SELECT   FRG.REQUEST_GROUP_NAME,
         DECODE(FRGU.REQUEST_UNIT_TYPE,  'S', FRSV.REQUEST_SET_NAME,  'P', FCPV.CONCURRENT_PROGRAM_NAME) R_CODE,
         DECODE(FRGU.REQUEST_UNIT_TYPE,  'S', FRSV.USER_REQUEST_SET_NAME,  'P', FCPV.USER_CONCURRENT_PROGRAM_NAME) R_NAME,
         'V' N
FROM     FND_REQUEST_GROUPS FRG,
         FND_REQUEST_GROUP_UNITS FRGU,
         FND_CONCURRENT_PROGRAMS_VL FCPV,
         FND_REQUEST_SETS_VL FRSV
WHERE    1 = 1
AND      FRG.REQUEST_GROUP_NAME = 'FS_¥[·ùIT_R'
AND      FRG.REQUEST_GROUP_ID = FRGU.REQUEST_GROUP_ID
AND      FRGU.REQUEST_UNIT_ID = FCPV.CONCURRENT_PROGRAM_ID(+)
AND      FRGU.REQUEST_UNIT_ID = FRSV.REQUEST_SET_ID(+)
ORDER BY FCPV.CONCURRENT_PROGRAM_NAME